<a href="https://colab.research.google.com/github/dipu-malitha/Neural-Network/blob/main/Activation_Function_for_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import numpy for creating equatiom**

In [1]:
import numpy as np

**1. ReLU-Rectified Linear Unit (Hidden Layer)**

In [3]:
def ReLU(x):
  return np.maximum(0,x)

In [8]:
x= ReLU(-10)
y= ReLu(10)
print(x)
print(y)

0
10


In [9]:
ReLU(np.array([-10,10]))

array([ 0, 10])

**2.Leaky ReLU (Hidden Layer)**

In [12]:
def Leaky_ReLU(x, alpha = 0.1):
  return np.where(x>0,x, x*alpha)

In [31]:
Leaky_ReLU(-.5)

array(-0.05)

In [14]:
Leaky_ReLU(10)

array(10.)

In [25]:
Leaky_ReLU(np.array([-5,5]))

array([-0.5,  5. ])

**3.ELU-Exponential lenear Unit ( Hidden Layer)**

In [43]:
def ELU (x,alpha=1.0):
  return np.where(x>0, x, alpha*(np.exp(x)-1))

In [44]:
ELU(5)

array(5.)

In [46]:
ELU(np.array([-1,0,0,1,2]))

array([-0.63212056,  0.        ,  0.        ,  1.        ,  2.        ])

**4.Sigmoid ( Outlayer and Binary classification problem)**

In [54]:
def sigmoid(x):
  return 1/ (1 + np.exp(x))

In [55]:
sigmoid(5)

np.float64(0.0066928509242848554)

In [56]:
sigmoid(np.array([1,2,0,-1]))

array([0.26894142, 0.11920292, 0.5       , 0.73105858])

**5.Softmax (Outlayer and multiclass problems)**

In [57]:
def softmax (x):
  e_x = np.exp(x - np.max(x))
  return e_x / e_x.sum(axis=0)

In [65]:
softmax(np.array([1,2,0,-1]))

array([0.23688282, 0.64391426, 0.08714432, 0.0320586 ])

**6.Swish (Hidden Layer)**

In [71]:
def swish (x, beta = 1.0):
  return x * sigmoid(beta* x)

In [72]:
swish(5)

np.float64(0.03346425462142428)

In [73]:
swish(np.array([-1,0,1,2]))

array([-0.73105858,  0.        ,  0.26894142,  0.23840584])

**7.Lenear(Output layer)**

In [74]:
def linear(x):
  return x

In [75]:
linear(np.array([-1,0,1,2]))

array([-1,  0,  1,  2])

**8. Tanh (Hyperbolic Tangent)**

In [76]:
def tanh(x):
  return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [77]:
tanh(5)

np.float64(0.999909204262595)

In [78]:
tanh(np.array([-1,0,1,2]))

array([-0.76159416,  0.        ,  0.76159416,  0.96402758])